# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'MyPokedex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for MyPokedex
  pod 'Alamofire', '~> 5.1'
  pod 'SDWebImage', '~> 5.0'
end
